POST http://localhost:5000/notes
Content-Type: application/json

{
    "note_title": "API get",
    "note_content": "Fech the API during the break period",
    "create_date": "2023-7-28"
}


###get all the notes
GET  http://localhost:5000/notes

###get one note
GET  http://localhost:5000/notes/aaffd8b8-803d-4c3f-a9a5-78f37adfa936

###Update one note
PUT  http://localhost:5000/notes/8929369f-9865-497e-b523-dee66a72fef9
Content-Type: application/json

{
    "note_title": "API push",
    "note_content": "Get the API during the break period",
    "create_date": "2024-10-28"
}

###delete note
DELETE http://localhost:5000/notes/aaffd8b8-803d-4c3f-a9a5-78f37adfa936